#' @title Compute Base-Out States on Retrosheet Data
#' @export
#' @param data A data frame of Retrosheet event data generated by
#' [baseballr::retrosheet_data()].
#' @param ... currently ignored
#' @return A tibble with nine additional variables provided information
#' about the beginning and ending base-out state for the play.
#' In particular `state` is the initial state, and `new_state` is
#' the resulting state.
#' @seealso [baseballr::retrosheet_data()]
#' @source \url{https://beanumber.github.io/abdwr3e/05-runsexpectancy.html#sec-runsexpectancy}
#' @examples
#' \dontrun{
#' if (require(baseballr)) {
#'   retro2016 <- baseballr::retrosheet_data(tempdir(), 2016)
#'   events <- retro2016[[1]][["events"]]
#'   events_states <- retrosheet_add_states(events)
#' }
#' }
retrosheet_add_states <- function(data, ...) {
  data |>
    dplyr::mutate(
      bases = paste0(
        ifelse(base1_run_id == "", 0, 1),
        ifelse(base2_run_id == "", 0, 1),
        ifelse(base3_run_id == "", 0, 1)
      ),
      state = paste(bases, outs_ct),
      is_runner1 = as.numeric(
        run1_dest_id == 1 | bat_dest_id == 1
      ),
      is_runner2 = as.numeric(
        run1_dest_id == 2 | run2_dest_id == 2 |
          bat_dest_id == 2
      ),
      is_runner3 = as.numeric(
        run1_dest_id == 3 | run2_dest_id == 3 |
          run3_dest_id == 3 | bat_dest_id == 3
      ),
      new_outs = outs_ct + event_outs_ct,
      new_bases = paste0(is_runner1, is_runner2, is_runner3),
      new_state = paste(new_bases, new_outs),
      runs_scored =
        (bat_dest_id > 3) + (run1_dest_id > 3) +
          (run2_dest_id > 3) + (run3_dest_id > 3)
    )
}

#' @rdname retrosheet_add_states
#' @export
#'

retrosheet_add_counts <- function(data, ...) {
  b <- "[BIPV]"
  s <- "[CFKLMOQRST]"
  data |>
    dplyr::mutate(
      pseq = gsub("[.>123+*N]", "", pitch_seq_tx),
      c00 = TRUE,
      c10 = grepl("^[BIPV]", pseq),
      c01 = grepl("^[CFKLMOQRST]", pseq),
      c20 = grepl("^[BIPV]{2}", pseq),
      c30 = grepl("^[BIPV]{3}", pseq),
      c02 = grepl("^[CFKLMOQRST]{2}", pseq),
      c11 = grepl(
        paste0(
          "^", s, b,
          "|", b, s
        ), pseq
      ),
      c21 = grepl(
        paste0(
          "^", s, b, b,
          "|", b, s, b,
          "|", b, b, s
        ),
        pseq
      ),
      c31 = grepl(
        paste0(
          "^", s, b, b, b,
          "|", b, s, b, b,
          "|", b, b, s, b,
          "|", b, b, b, s
        ), pseq
      ),
      c12 = grepl(
        paste0(
          "^", b, s, s,
          "|", s, b, s,
          "|", s, s, "[FR]*", b
        ), pseq
      ),
      c22 = grepl(
        paste0(
          "^", b, b, s, s,
          "|", b, s, b, s,
          "|", b, s, s, "[FR]*", b,
          "|", s, b, b, s,
          "|", s, b, s, "[FR]*", b,
          "|", s, s, "[FR]*", b, "[FR]*", b
        ), pseq
      ),
      c32 = grepl(
        paste0("^", s, "*", b, s, "*", b, s, "*", b), pseq
      ) & grepl(
        paste0("^", b, "*", s, b, "*", s), pseq
      )
    )
}
